apiVersion: v1                    
kind: Namespace
metadata:
  name: acm-demo                             
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: acm-demo
  namespace: acm-demo
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - acm-demo
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: githubcom-nkunnath-sample-wordpress
  namespace: acm-demo
spec:
  type: Git
  pathname: 'https://github.com/nkunnath/sample-wordpress'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: wordpress
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: acm-demo
  name: acm-demo-subscription-1
  namespace: acm-demo
spec:
  channel: acm-demo/githubcom-nkunnath-sample-wordpress
  placement:
    placementRef:
      kind: PlacementRule
      name: acm-demo-placement-1
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: acm-demo
  name: acm-demo-placement-1
  namespace: acm-demo
spec:
  clusterSelector:
    matchLabels:
      'local-cluster': 'true'