
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: docker.io/bitnami/mariadb:10.6
        name: mariadb
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MARIADB_DATABASE
          value: "bitnami_wordpress"
        - name: MARIADB_USER
          value: "bn_wordpress"
        volumeMounts:
        - name: mariadb-persistent-storage
          mountPath: /bitnami/mariadb
      - image: docker.io/bitnami/wordpress-nginx:6
        name: wordpress
        env:
        - name: WORDPRESS_DATABASE_HOST
          value: "mariadb"
        - name: WORDPRESS_DATABASE_PORT_NUMBER
          value: "3306"
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: WORDPRESS_DATABASE_NAME
          value: "bitnami_wordpress"
        - name: WORDPRESS_DATABASE_USER
          value: "bn_wordpress"
        ports:
        - containerPort: 8080
        - containerPort: 8443
        - containerPort: 3306
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /bitnami/wordpress
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
      - name: mariadb-persistent-storage
        persistentVolumeClaim:
          claimName: md-pv-claim
