apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: "80"
    - name: "443"
      port: 443
      targetPort: 8443
  selector:
    app: wordpress
    tier: frontend
  type: ClusterIP