apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-acm-csi-nutanixcsistorage
  namespace: acm-csi-demo
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: acm-csi-nutanixcsistorage
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: crd.nutanix.com/v1alpha1
            kind: NutanixCsiStorage
            metadata:
              annotations:
                operator-sdk/primary-resource: /ntnx-csi-scc
                operator-sdk/primary-resource-type: SecurityContextConstraints.security.openshift.io
              finalizers:
              - helm.sdk.operatorframework.io/uninstall-release
              name: nutanixcsistorage
              namespace: openshift-cluster-csi-drivers
            spec: {}
        remediationAction: enforce
        severity: high
  remediationAction: enforce