apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-acm-csi-operatorgroup
  namespace: acm-csi-demo
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: acm-csi-operatorgroup
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: operators.coreos.com/v1
            kind: OperatorGroup
            metadata:
              annotations:
                olm.providedAPIs: NutanixCsiStorage.v1alpha1.crd.nutanix.com
              name: openshift-cluster-csi-drivers-og
              namespace: openshift-cluster-csi-drivers
            spec:
              targetNamespaces:
              - openshift-cluster-csi-drivers
              upgradeStrategy: Default
        remediationAction: enforce
        severity: high
  remediationAction: enforce