apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-acm-csi-subscription
  namespace: acm-csi-demo
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: acm-csi-subscription
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: operators.coreos.com/v1alpha1
            kind: Subscription
            metadata:
              name: nutanixcsioperator
              namespace: openshift-cluster-csi-drivers
            spec:
              channel: stable
              installPlanApproval: Automatic
              name: nutanixcsioperator
              source: certified-operators
              sourceNamespace: openshift-marketplace
              startingCSV: nutanixcsioperator.v2.6.1
        remediationAction: enforce
        severity: high
  remediationAction: enforce